CREATE TABLE MEMBER (
	id VARCHAR(100) PRIMARY KEY,
	NAME VARCHAR(100),
	PASSWORD VARCHAR(100),
	email VARCHAR(100),
	address VARCHAR(100)
);


CREATE TABLE ACCOUNT(
	id VARCHAR(100) PRIMARY KEY,
	NAME VARCHAR(100),
	balance INT,
	type VARCHAR(100),
	grade VARCHAR(100)
);